name: Scheduled or Manual Trigger

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (UTC)
  workflow_dispatch:

jobs:
  call-main:
    permissions:
      contents: write
    uses: ./.github/workflows/fetch-game-data.yml
    secrets: inherit
